"""Ignore-list handling for static spec analysis."""
from __future__ import annotations

import fnmatch
from pathlib import Path

DEFAULT_REDEPLOYIGNORE = """# .redeployignore — files excluded from deployment sync
# Auto-generated by redeploy. Edit as needed.

# Python
__pycache__/
*.pyc
*.pyo
.venv/
env/
venv/

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Build artifacts
dist/
build/
*.egg-info/
node_modules/
target/

# Version control (already handled by git, but explicit here)
.git/
"""


def ensure_redeployignore(base_dir: Path) -> None:
    """Create .redeployignore with sensible defaults if it doesn't exist."""
    path = base_dir / ".redeployignore"
    if not path.exists():
        path.write_text(DEFAULT_REDEPLOYIGNORE)


class IgnoreList:
    """Read .gitignore and .redeployignore patterns and test if paths are ignored."""

    def __init__(self, base_dir: Path):
        self.patterns: list[str] = []
        self._load(base_dir / ".gitignore")
        self._load(base_dir / ".redeployignore")

    def _load(self, path: Path) -> None:
        if not path.exists():
            return
        for line in path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                self.patterns.append(line)

    def is_ignored(self, rel_path: Path) -> bool:
        parts = rel_path.parts
        name = rel_path.name

        for pattern in self.patterns:
            pat = pattern.rstrip("/")
            if fnmatch.fnmatch(name, pat):
                return True
            for part in parts:
                if fnmatch.fnmatch(part, pat):
                    return True
            if "/" in pattern:
                pat_parts = pat.split("/")
                for start in range(len(parts) - len(pat_parts) + 1):
                    if all(
                        fnmatch.fnmatch(parts[start + i], pp)
                        for i, pp in enumerate(pat_parts)
                    ):
                        return True
        return False


# Backward-compatible alias for tests.
_IgnoreList = IgnoreList
