flowchart LR
%% generated in 0.02s
    subgraph examples__redeploy_iac_parsers
        examples__redeploy_iac_parsers__gitops_ci__GitLabCIGitOpsParser__can_parse["can_parse"]
        examples__redeploy_iac_parsers__helm_kustomize__HelmTemplatesParser__parse["parse"]
        examples__redeploy_iac_parsers__gitops_ci___is_gitops_command["_is_gitops_command"]
    end
    subgraph redeploy__analyze
        redeploy__analyze__checkers__docker_build__DockerBuildChecker___check_remote_context["_check_remote_context"]
        redeploy__analyze__checkers__docker_build__DockerBuildChecker__check["check"]
        redeploy__analyze__checkers__binary__BinaryChecker__check["check"]
        redeploy__analyze__spec_analyzer__SpecAnalyzer__analyze_file["analyze_file"]
        redeploy__analyze__checkers__compose__ComposeChecker__check["check"]
        redeploy__analyze__checkers__command_ref__CommandRefChecker___check_external_ref["_check_external_ref"]
        redeploy__analyze__checkers__binary__extract_binaries["extract_binaries"]
        redeploy__analyze__preflight_schema___collect_local_artifacts["_collect_local_artifacts"]
        redeploy__analyze__checkers__path__CommandPathChecker__check["check"]
        redeploy__analyze__checkers__docker_build__collect_sync_mappings["collect_sync_mappings"]
        redeploy__analyze__ignore__ensure_redeployignore["ensure_redeployignore"]
        redeploy__analyze__checkers__compose___check_volumes["_check_volumes"]
        redeploy__analyze__checkers__docker_build__parse_docker_build["parse_docker_build"]
        redeploy__analyze__preflight_schema___collect_remote_checks["_collect_remote_checks"]
        redeploy__analyze__checkers__docker_build__resolve_local_dockerfile["resolve_local_dockerfile"]
        redeploy__analyze__checkers__path__resolve_local_path["resolve_local_path"]
        redeploy__analyze__checkers__compose___check_build_section["_check_build_section"]
        redeploy__analyze__preflight_schema___resolve_local_path["_resolve_local_path"]
        redeploy__analyze__checkers__docker_build__match_local_src["match_local_src"]
        redeploy__analyze__checkers__compose___is_ignored["_is_ignored"]
        redeploy__analyze__checkers__path__PathChecker___check_field["_check_field"]
        redeploy__analyze__preflight_schema__generate_preflight_schema["generate_preflight_schema"]
        redeploy__analyze__checkers__compose___check_env_files["_check_env_files"]
        redeploy__analyze__checkers__compose__scan_compose_file["scan_compose_file"]
        redeploy__analyze__preflight_schema___resolve_command_refs["_resolve_command_refs"]
        redeploy__analyze__checkers__path__is_inside["is_inside"]
        redeploy__analyze__models__AnalysisResult__add["add"]
        redeploy__analyze__spec_analyzer__SpecAnalyzer____init__["__init__"]
        redeploy__analyze__ignore__IgnoreList__is_ignored["is_ignored"]
    end
    subgraph redeploy__apply
        redeploy__apply__state__default_state_path["default_state_path"]
        redeploy__apply__executor__Executor___rollback["_rollback"]
        redeploy__apply__handlers___format_step_output["_format_step_output"]
        redeploy__apply__handlers___parse_container_statuses["_parse_container_statuses"]
        redeploy__apply__handlers__run_ensure_config_line["run_ensure_config_line"]
        redeploy__apply__rollback__rollback_steps["rollback_steps"]
        redeploy__apply__state_apply__apply_state["apply_state"]
        redeploy__apply__executor__Executor____init__["__init__"]
        redeploy__apply__handlers___resolve_command_ref["_resolve_command_ref"]
        redeploy__apply__handlers__run_inline_script["run_inline_script"]
        redeploy__apply__state_apply___update_kanshi["_update_kanshi"]
        redeploy__apply__state___now_iso["_now_iso"]
        redeploy__apply__executor__Executor___execute_step["_execute_step"]
        redeploy__apply__state_apply__detect_handler["detect_handler"]
        redeploy__apply__state__state_key["state_key"]
        redeploy__apply__utils__run_container_build__run_container_build["run_container_build"]
        redeploy__apply__state_apply__HardwareStateHandler__apply["apply"]
        redeploy__apply__state___slug["_slug"]
        redeploy__apply__handlers__run_docker_build["run_docker_build"]
        redeploy__apply__handlers__run_rsync["run_rsync"]
        redeploy__apply__handlers__run_podman_build["run_podman_build"]
        redeploy__apply__handlers___ensure_remote_parent_dir["_ensure_remote_parent_dir"]
        redeploy__apply__handlers__run_ensure_autostart_entry["run_ensure_autostart_entry"]
        redeploy__apply__handlers___all_containers_healthy["_all_containers_healthy"]
        redeploy__apply__handlers__run_ssh["run_ssh"]
        redeploy__apply__state__ResumeState__save["save"]
        redeploy__apply__state__ResumeState__reset["reset"]
        redeploy__apply__handlers__run_scp["run_scp"]
        redeploy__apply__handlers__run_docker_health_wait["run_docker_health_wait"]
        redeploy__apply__handlers__run_raspi_config["run_raspi_config"]
    end
    subgraph redeploy__audit
        redeploy__audit__paths__extract_port["extract_port"]
        redeploy__audit__paths__normalize_path["normalize_path"]
        redeploy__audit__audit_spec["audit_spec"]
        redeploy__audit__extractor__Extractor___from_target["_from_target"]
    end
    subgraph redeploy__blueprint
        redeploy__blueprint__sources__infra__infer_app_url["infer_app_url"]
        redeploy__blueprint__sources__compose__merge_compose_files["merge_compose_files"]
        redeploy__blueprint__sources__compose___parse_compose_ports["_parse_compose_ports"]
        redeploy__blueprint__sources__compose___parse_compose_env["_parse_compose_env"]
        redeploy__blueprint__extractor__extract_blueprint["extract_blueprint"]
        redeploy__blueprint__sources__compose___parse_compose_healthcheck["_parse_compose_healthcheck"]
        redeploy__blueprint__sources__compose___merge_compose["_merge_compose"]
        redeploy__blueprint__sources__compose___parse_compose_volumes["_parse_compose_volumes"]
        redeploy__blueprint__sources__hardware__build_hw_requirements["build_hw_requirements"]
        redeploy__blueprint__generators__docker_compose__generate_twin["generate_twin"]
        redeploy__blueprint__generators__docker_compose___build_service["_build_service"]
    end
    subgraph redeploy__cli
        redeploy__cli__commands__plan_apply___build_checksum_verification["_build_checksum_verification"]
        redeploy__cli__commands__gh_workflow___has_workflow_dispatch["_has_workflow_dispatch"]
        redeploy__cli__commands__version__scanner___derive_scanned_package_name["_derive_scanned_package_name"]
        redeploy__cli__commands__plugin__plugin_cmd["plugin_cmd"]
        redeploy__cli__commands__bump_fix___bump_patch["_bump_patch"]
        redeploy__cli__commands__mcp_cmd__mcp_cmd["mcp_cmd"]
        redeploy__cli__commands__version__scanner___format_version_scan_source_status["_format_version_scan_source_st"]
        redeploy__cli__commands__state___list_checkpoints["_list_checkpoints"]
        redeploy__cli__display__print_import_spec["print_import_spec"]
        redeploy__cli__commands__plan_apply___apply_manifest_to_spec["_apply_manifest_to_spec"]
        redeploy__cli__commands__version__monorepo___set_monorepo_version["_set_monorepo_version"]
        redeploy__cli__display___get_status_color["_get_status_color"]
        redeploy__cli__commands__gh_workflow__gh_workflow_analyze["gh_workflow_analyze"]
        redeploy__cli__commands__bump_fix___update_migration_header["_update_migration_header"]
        redeploy__cli__commands__hardware___probe_hardware["_probe_hardware"]
        redeploy__cli__commands__bump_fix___find_spec["_find_spec"]
        redeploy__cli__commands__gh_workflow___find_repo_root["_find_repo_root"]
        redeploy__cli__commands__version__commands__version_verify["version_verify"]
        redeploy__cli__commands__export___find_export_source["_find_export_source"]
        redeploy__cli__commands__version__commands__version_list["version_list"]
        redeploy__cli__commands__device_map___render["_render"]
        redeploy__cli__commands__state__state_cmd["state_cmd"]
        redeploy__cli__commands__device_map_renderers___build_header_panel["_build_header_panel"]
        redeploy__cli__commands__export___export_to_css["_export_to_css"]
        redeploy__cli__commands__plan_apply___resolve_audit_entry["_resolve_audit_entry"]
        redeploy__cli__commands__target__target["target"]
        redeploy__cli__commands__version__monorepo___create_version_set_git["_create_version_set_git"]
        redeploy__cli__commands__version__release___create_release_tags["_create_release_tags"]
        redeploy__cli__commands__version__scanner___is_scannable_version_path["_is_scannable_version_path"]
        redeploy__cli__commands__plan_apply___render_markdown_report["_render_markdown_report"]
        redeploy__cli__commands__gh_workflow___load_yaml["_load_yaml"]
        redeploy__cli__commands__version__helpers___load_live_version_diff["_load_live_version_diff"]
        redeploy__cli__display__print_inspect_environments["print_inspect_environments"]
        redeploy__cli__commands__lint__lint["lint"]
        redeploy__cli__commands__version__helpers___run_version_diff_for_manifest["_run_version_diff_for_manifest"]
        redeploy__cli__commands__gh_workflow__gh_workflow_list["gh_workflow_list"]
        redeploy__cli__commands__exec____extract_script_for_ref["_extract_script_for_ref"]
        redeploy__cli__commands__version__helpers___build_package_version_manifest["_build_package_version_manifes"]
        redeploy__cli__commands__import____copy_plugin_template["_copy_plugin_template"]
        redeploy__cli__display__print_inspect_app_metadata["print_inspect_app_metadata"]
        redeploy__cli__commands__version__monorepo___create_version_set_taggers["_create_version_set_taggers"]
        redeploy__cli__commands__version__scanner___scan_package_version_manifests["_scan_package_version_manifest"]
        redeploy__cli__commands__version__scanner___print_version_scan_review["_print_version_scan_review"]
        redeploy__cli__core__run_detect_workflow["run_detect_workflow"]
        redeploy__cli__commands__gh_workflow___workflows_dir["_workflows_dir"]
        redeploy__cli__commands__version__release___resolve_package_release_changelog_config["_resolve_package_release_chang"]
        redeploy__cli__commands__version__helpers___resolve_package_release_changelog_config["_resolve_package_release_chang"]
        redeploy__cli__commands__bump_fix___prompt_choose_spec["_prompt_choose_spec"]
        redeploy__cli__core__load_spec_or_exit["load_spec_or_exit"]
        redeploy__cli__commands__gh_workflow__gh_workflow_run["gh_workflow_run"]
        redeploy__cli__commands__state___get_state_path["_get_state_path"]
        redeploy__cli__commands__bump_fix___bump_version_file["_bump_version_file"]
        redeploy__cli__display___print_spec_metadata["_print_spec_metadata"]
        redeploy__cli__display__print_workflow_summary_table["print_workflow_summary_table"]
        redeploy__cli__commands__exec___exec_cmd["exec_cmd"]
        redeploy__cli__display__print_workflow_host_details["print_workflow_host_details"]
        redeploy__cli__commands__bump_fix___detect_version["_detect_version"]
        redeploy__cli__commands__device_map_renderers___build_services_table["_build_services_table"]
        redeploy__cli__commands__exec____extract_all_scripts["_extract_all_scripts"]
        redeploy__cli__commands__gh_workflow___trigger_list["_trigger_list"]
        redeploy__cli__commands__version__scanner___summarize_version_scan_group["_summarize_version_scan_group"]
        redeploy__cli__commands__version__scanner___review_detected_sources_interactively["_review_detected_sources_inter"]
        redeploy__cli__commands__plan_apply___default_report_path["_default_report_path"]
        redeploy__cli__commands__device_map___execute_query_device_map["_execute_query_device_map"]
        redeploy__cli__commands__device_map_renderers___build_drm_table["_build_drm_table"]
        redeploy__cli__commands__version__scanner___default_keep_scanned_source["_default_keep_scanned_source"]
        redeploy__cli__display__print_inspect_templates["print_inspect_templates"]
        redeploy__cli___resolve_device["_resolve_device"]
        redeploy__cli__commands__version__helpers___resolve_monorepo_targets["_resolve_monorepo_targets"]
        redeploy__cli__commands__version__monorepo___finalize_monorepo_version_set["_finalize_monorepo_version_set"]
        redeploy__cli__commands__version__helpers___print_verify_result["_print_verify_result"]
        redeploy__cli__commands__device_map_renderers__render_yaml["render_yaml"]
        redeploy__cli__display___format_workflow_header["_format_workflow_header"]
        redeploy__cli__display___print_host_header["_print_host_header"]
        redeploy__cli__commands__version__helpers___load_spec_version_diff["_load_spec_version_diff"]
        redeploy__cli__core__resolve_device["resolve_device"]
        redeploy__cli__commands__workflow__workflow_cmd["workflow_cmd"]
        redeploy__cli__display___print_template_match["_print_template_match"]
        redeploy__cli__commands__import____print_plugin_templates["_print_plugin_templates"]
        redeploy__cli__commands__bump_fix___find_version_file["_find_version_file"]
        redeploy__cli__commands__device_map_renderers__render_json["render_json"]
        redeploy__cli__commands__hardware___execute_query["_execute_query"]
        redeploy__cli__commands__version__helpers___bump_single["_bump_single"]
        redeploy__cli__core__find_manifest_path["find_manifest_path"]
        redeploy__cli__display___print_services_table["_print_services_table"]
        redeploy__cli__commands__diagnose__diagnose["diagnose"]
        redeploy__cli__commands__version__scanner___regex_version_scan_specs["_regex_version_scan_specs"]
        redeploy__cli__display__generate_workflow_output_yaml["generate_workflow_output_yaml"]
        redeploy__cli__commands__gh_workflow___resolve_workflow_identifier["_resolve_workflow_identifier"]
        redeploy__cli__commands__import____examples_plugin_dir["_examples_plugin_dir"]
        redeploy__cli__commands__blueprint___execute_query_blueprint["_execute_query_blueprint"]
        redeploy__cli__commands__version__monorepo___print_monorepo_set_dry_run["_print_monorepo_set_dry_run"]
        redeploy__cli__commands__version__release___format_release_tag["_format_release_tag"]
        redeploy__cli__display___get_plugin_hint["_get_plugin_hint"]
        redeploy__cli__display__generate_workflow_output_css["generate_workflow_output_css"]
        redeploy__cli__commands__version__scanner___detect_version_sources_in_dir["_detect_version_sources_in_dir"]
        redeploy__cli__commands__workflow___execute_workflow["_execute_workflow"]
        redeploy__cli__commands__version__helpers___print_source_drift_status["_print_source_drift_status"]
        redeploy__cli__commands__gh_workflow___resolve_repo_root["_resolve_repo_root"]
        redeploy__cli__core__load_spec_with_manifest["load_spec_with_manifest"]
        redeploy__cli__cli["cli"]
        redeploy__cli__commands__version__release___update_monorepo_release_changelogs["_update_monorepo_release_chang"]
        redeploy__cli__commands__bump_fix___update_quadlet_service_version["_update_quadlet_service_versio"]
        redeploy__cli___setup_logging["_setup_logging"]
        redeploy__cli__commands__version__scanner___detect_source_version["_detect_source_version"]
        redeploy__cli__commands__device_map_renderers__render_rich["render_rich"]
        redeploy__cli__query__execute_query["execute_query"]
        redeploy__cli__commands__export___load_manifest_from_css["_load_manifest_from_css"]
        redeploy__cli__commands__hardware___apply_transform["_apply_transform"]
        redeploy__cli__commands__version__scanner___classify_version_scan_source_confidence["_classify_version_scan_source_"]
        redeploy__cli__commands__device_map_renderers___build_issues_table["_build_issues_table"]
        redeploy__cli__commands__prompt_cmd__prompt_cmd["prompt_cmd"]
        redeploy__cli__commands__version__scanner___print_version_scan_group["_print_version_scan_group"]
        redeploy__cli__commands__version__helpers___resolve_package_release_git_config["_resolve_package_release_git_c"]
        redeploy__cli__commands__state___show_checkpoint["_show_checkpoint"]
        redeploy__cli__commands__gh_workflow___on_section["_on_section"]
        redeploy__cli__commands__gh_workflow___collect_workflow_meta["_collect_workflow_meta"]
        redeploy__cli__display___print_alternatives["_print_alternatives"]
        redeploy__cli__commands__bump_fix__bump_cmd["bump_cmd"]
        redeploy__cli__commands__blueprint__show["show"]
        redeploy__cli__commands__export__export_cmd["export_cmd"]
        redeploy__cli__commands__version__release___update_release_changelog["_update_release_changelog"]
        redeploy__cli__commands__plan_apply___write_markdown_report["_write_markdown_report"]
        redeploy__cli__commands__import____plugin_templates["_plugin_templates"]
        redeploy__cli__commands__hardware___apply_fix["_apply_fix"]
        redeploy__cli__display__print_inspect_workflows["print_inspect_workflows"]
        redeploy__cli__commands__version__scanner___version_scan_specs["_version_scan_specs"]
        redeploy__cli__display___print_workflow_step["_print_workflow_step"]
        redeploy__cli__commands__inspect__inspect["inspect"]
        redeploy__cli__commands__version__scanner___read_detected_source_versions["_read_detected_source_versions"]
        redeploy__cli__commands__version__scanner___report_version_scan_conflict["_report_version_scan_conflict"]
        redeploy__cli__commands__inspect___find_css_path["_find_css_path"]
        redeploy__cli__commands__version__scanner___iter_version_scan_groups["_iter_version_scan_groups"]
    end
    subgraph redeploy__config_apply
        redeploy__config_apply__applier__apply_config_file["apply_config_file"]
        redeploy__config_apply__handlers__display___validate_display_inputs["_validate_display_inputs"]
        redeploy__config_apply__loader__load_config_file["load_config_file"]
        redeploy__config_apply__handlers__display__apply_display_transform["apply_display_transform"]
        redeploy__config_apply__applier___normalize_hardware["_normalize_hardware"]
        redeploy__config_apply__applier__apply_config_dict["apply_config_dict"]
    end
    subgraph redeploy__detect
        redeploy__detect__probes__probe_iptables_dnat["probe_iptables_dnat"]
        redeploy__detect__templates___build_templates["_build_templates"]
        redeploy__detect__probes__detect_conflicts["detect_conflicts"]
        redeploy__detect__workflow__DetectionWorkflow___collect_hosts["_collect_hosts"]
        redeploy__detect__hardware_rules___op3_diag_to_hw_diag["_op3_diag_to_hw_diag"]
        redeploy__detect__hardware_rules___hw_info_to_dict["_hw_info_to_dict"]
        redeploy__detect__hardware_rules__analyze["analyze"]
        redeploy__detect__workflow__DetectionWorkflow___probe_ssh["_probe_ssh"]
        redeploy__detect__templates___load_templates_from_yaml["_load_templates_from_yaml"]
        redeploy__detect__detector__Detector__run["run"]
        redeploy__detect__templates__TemplateEngine__detect["detect"]
        redeploy__detect__templates__build_context["build_context"]
        redeploy__detect__hardware__probe_hardware["probe_hardware"]
        redeploy__detect__hardware___wrap_remote_probe["_wrap_remote_probe"]
        redeploy__detect__probes__probe_ports["probe_ports"]
        redeploy__detect__detector__Detector__probe_hardware["probe_hardware"]
        redeploy__detect__probes__probe_runtime["probe_runtime"]
    end
    subgraph redeploy__discovery
        redeploy__discovery___run_ssh_probe["_run_ssh_probe"]
        redeploy__discovery___merge["_merge"]
        redeploy__discovery___ping_sweep["_ping_sweep"]
        redeploy__discovery___tcp_reachable["_tcp_reachable"]
        redeploy__discovery___detect_strategy_remote["_detect_strategy_remote"]
        redeploy__discovery___scan_mdns["_scan_mdns"]
        redeploy__discovery___run["_run"]
        redeploy__discovery___build_ssh_command["_build_ssh_command"]
        redeploy__discovery___scan_arp_cache["_scan_arp_cache"]
        redeploy__discovery___scan_known_hosts["_scan_known_hosts"]
        redeploy__discovery__auto_probe["auto_probe"]
        redeploy__discovery___probe_ssh["_probe_ssh"]
        redeploy__discovery___collect_ssh_keys["_collect_ssh_keys"]
        redeploy__discovery___parse_probe_output["_parse_probe_output"]
        redeploy__discovery___infer_strategy["_infer_strategy"]
        redeploy__discovery___try_ssh_credentials["_try_ssh_credentials"]
        redeploy__discovery___is_ip["_is_ip"]
        redeploy__discovery___detect_local_subnet["_detect_local_subnet"]
        redeploy__discovery__discover["discover"]
        redeploy__discovery___build_probe_command["_build_probe_command"]
        redeploy__discovery___parse_probe_input["_parse_probe_input"]
    end
    subgraph redeploy__dsl
        redeploy__dsl__loader___build_manifest["_build_manifest"]
        redeploy__dsl__loader__templates_to_css["templates_to_css"]
        redeploy__dsl__parser__RedeployDSLParser__parse["parse"]
        redeploy__dsl__loader__manifest_to_css["manifest_to_css"]
        redeploy__dsl__loader___build_workflows["_build_workflows"]
        redeploy__dsl__loader___build_from_nodes["_build_from_nodes"]
        redeploy__dsl__loader__load_css["load_css"]
        redeploy__dsl__parser__DSLNode____repr__["__repr__"]
        redeploy__dsl__loader__load_css_text["load_css_text"]
        redeploy__dsl__loader___condition_key["_condition_key"]
        redeploy__dsl__loader___build_templates["_build_templates"]
        redeploy__dsl__parser___strip_comments["_strip_comments"]
    end
    subgraph redeploy__dsl_python
        redeploy__dsl_python__steps__ssh["ssh"]
        redeploy__dsl_python__steps__version_check["version_check"]
        redeploy__dsl_python__runner__PythonMigrationRunner__list_migrations["list_migrations"]
    end
    subgraph redeploy__fleet
        redeploy__fleet__Fleet__merge["merge"]
        redeploy__fleet__Fleet__get["get"]
        redeploy__fleet__Fleet__from_registry["from_registry"]
        redeploy__fleet__Fleet____init__["__init__"]
    end
    subgraph redeploy__hardware
        redeploy__hardware__panels__infer_from_hardware["infer_from_hardware"]
        redeploy__hardware__fixes___detect_port["_detect_port"]
        redeploy__hardware__fixes__generate_fix_plan["generate_fix_plan"]
        redeploy__hardware__config_txt__ensure_lines["ensure_lines"]
        redeploy__hardware__fixes__fix_dsi_not_enabled["fix_dsi_not_enabled"]
        redeploy__hardware__raspi_config__build_raspi_config_command["build_raspi_config_command"]
        redeploy__hardware__kiosk__browsers__BrowserKioskProfile__build_launch_cmd["build_launch_cmd"]
        redeploy__hardware__kiosk__autostart__ensure_autostart_entry["ensure_autostart_entry"]
        redeploy__hardware__config_txt__ensure_line["ensure_line"]
        redeploy__hardware__fixes__fix_enable_spi["fix_enable_spi"]
        redeploy__hardware__fixes__fix_enable_i2c["fix_enable_i2c"]
        redeploy__hardware__fixes___step["_step"]
    end
    subgraph redeploy__heal
        redeploy__heal__collect_diagnostics["collect_diagnostics"]
        redeploy__heal__runner__HealRunner___reload_migration["_reload_migration"]
        redeploy__heal__HealRunner__run["run"]
        redeploy__heal__parse_failed_step["parse_failed_step"]
        redeploy__heal__loop_detector__HealLoopDetector__observe["observe"]
        redeploy__heal__HealRunner___reload_migration["_reload_migration"]
        redeploy__heal__runner__HealRunner__run["run"]
        redeploy__heal__hint_provider___extract_step_block["_extract_step_block"]
        redeploy__heal__HealLoopDetector__observe["observe"]
        redeploy__heal__hint_provider__collect_diagnostics["collect_diagnostics"]
        redeploy__heal__HealRunner___collect_diag_with_hint["_collect_diag_with_hint"]
        redeploy__heal__HealRunner___record_repair["_record_repair"]
        redeploy__heal__runner__HealRunner___heal_step["_heal_step"]
        redeploy__heal__apply_fix_to_spec["apply_fix_to_spec"]
        redeploy__heal__HealRunner___ask_and_apply_fix["_ask_and_apply_fix"]
        redeploy__heal__hint_provider__apply_fix_to_spec["apply_fix_to_spec"]
        redeploy__heal___ssh["_ssh"]
        redeploy__heal__hint_provider___parse_step_block["_parse_step_block"]
        redeploy__heal__hint_provider__ask_llm["ask_llm"]
        redeploy__heal__ask_llm["ask_llm"]
        redeploy__heal__write_repair_log["write_repair_log"]
        redeploy__heal__hint_provider___ssh["_ssh"]
    end
    subgraph redeploy__iac
        redeploy__iac__docker_compose__DockerComposeParser___resolve_image_and_build["_resolve_image_and_build"]
        redeploy__iac__config_hints__ConfigHintsParser___parse_k8s_yaml["_parse_k8s_yaml"]
        redeploy__iac__docker_compose___parse_volume["_parse_volume"]
        redeploy__iac__docker_compose__DockerComposeParser___parse_service_env["_parse_service_env"]
        redeploy__iac__docker_compose___env_dict["_env_dict"]
        redeploy__iac__docker_compose__DockerComposeParser___parse_service_depends_on["_parse_service_depends_on"]
        redeploy__iac__docker_compose__DockerComposeParser___parse_service_networks["_parse_service_networks"]
        redeploy__iac__docker_compose__DockerComposeParser___load_merged["_load_merged"]
        redeploy__iac__parsers__compose__DockerComposeParser___parse_depends_on["_parse_depends_on"]
        redeploy__iac__docker_compose___resolve_var["_resolve_var"]
        redeploy__iac__docker_compose___parse_port["_parse_port"]
        redeploy__iac__docker_compose__DockerComposeParser___parse_service_ports["_parse_service_ports"]
        redeploy__iac__docker_compose__DockerComposeParser___parse_service_volumes["_parse_service_volumes"]
        redeploy__iac__parsers__compose__DockerComposeParser___parse_service_networks["_parse_service_networks"]
    end
    subgraph redeploy__integrations
        redeploy__integrations__op3_bridge__snapshot_to_hardware_info["snapshot_to_hardware_info"]
        redeploy__integrations__op3_bridge__snapshot_to_device_map["snapshot_to_device_map"]
        redeploy__integrations__op3_bridge__snapshot_to_infra_state["snapshot_to_infra_state"]
    end
    subgraph redeploy__markpact
        redeploy__markpact__compiler___load_block_payload["_load_block_payload"]
        redeploy__markpact__parser___handle_fence_line["_handle_fence_line"]
        redeploy__markpact__compiler___extract_steps["_extract_steps"]
        redeploy__markpact__compiler___deep_merge["_deep_merge"]
        redeploy__markpact__parser__parse_markpact_text["parse_markpact_text"]
        redeploy__markpact__parser___parse_markpact_fence_info["_parse_markpact_fence_info"]
        redeploy__markpact__parser___normalize_section_id["_normalize_section_id"]
        redeploy__markpact__parser___check_heading["_check_heading"]
        redeploy__markpact__parser__extract_script_by_ref["extract_script_by_ref"]
        redeploy__markpact__parser__extract_script_from_markdown["extract_script_from_markdown"]
        redeploy__markpact__compiler___normalize_config_payload["_normalize_config_payload"]
        redeploy__markpact__parser__parse_markpact_file["parse_markpact_file"]
        redeploy__markpact__parser__resolve_script_ref["resolve_script_ref"]
        redeploy__markpact__compiler__compile_markpact_document["compile_markpact_document"]
        redeploy__markpact__parser__parse_markpact_file_with_refs["parse_markpact_file_with_refs"]
        redeploy__markpact__compiler__compile_markpact_document_to_data["compile_markpact_document_to_d"]
    end
    subgraph redeploy__mcp_server
        redeploy__mcp_server__exec_ssh["exec_ssh"]
        redeploy__mcp_server___validate_exec_ssh_inputs["_validate_exec_ssh_inputs"]
        redeploy__mcp_server__get_workspace["get_workspace"]
        redeploy__mcp_server__bump_version["bump_version"]
        redeploy__mcp_server___run["_run"]
        redeploy__mcp_server__plan_spec["plan_spec"]
        redeploy__mcp_server__nlp_command["nlp_command"]
        redeploy__mcp_server__serve["serve"]
        redeploy__mcp_server__schema["schema"]
        redeploy__mcp_server__run_spec["run_spec"]
        redeploy__mcp_server___redeploy_bin["_redeploy_bin"]
        redeploy__mcp_server__list_specs["list_specs"]
        redeploy__mcp_server__fix_spec["fix_spec"]
        redeploy__mcp_server__diagnose["diagnose"]
    end
    subgraph redeploy__models
        redeploy__models__manifest__ProjectManifest__find_css["find_css"]
        redeploy__models__manifest__ProjectManifest__find_and_load["find_and_load"]
        redeploy__models__spec___migrate_legacy_post_deploy["_migrate_legacy_post_deploy"]
        redeploy__models__spec__MigrationSpec__to_target_config["to_target_config"]
        redeploy__models__spec__MigrationSpec__from_file["from_file"]
    end
    subgraph redeploy__observe
        redeploy__observe__DeployAuditLog__record["record"]
    end
    subgraph redeploy__parse
        redeploy__parse___parse_section_line["_parse_section_line"]
        redeploy__parse___apply_network_line["_apply_network_line"]
        redeploy__parse___apply_git_line["_apply_git_line"]
        redeploy__parse___apply_system_line["_apply_system_line"]
        redeploy__parse___apply_health_line["_apply_health_line"]
        redeploy__parse__parse_container_line["parse_container_line"]
        redeploy__parse__parse_diagnostics["parse_diagnostics"]
    end
    subgraph redeploy__patterns
        redeploy__patterns__list_patterns["list_patterns"]
        redeploy__patterns___step["_step"]
        redeploy__patterns__BlueGreenPattern__expand["expand"]
        redeploy__patterns__CanaryPattern__expand["expand"]
        redeploy__patterns__get_pattern["get_pattern"]
        redeploy__patterns__RollbackOnFailurePattern__expand["expand"]
    end
    subgraph redeploy__plan
        redeploy__plan__planner__Planner___plan_pattern["_plan_pattern"]
    end
    subgraph redeploy__plugins
        redeploy__plugins__builtin__hardware_diagnostic___run_command["_run_command"]
        redeploy__plugins__PluginRegistry__names["names"]
        redeploy__plugins__builtin__hardware_diagnostic___detect_platform["_detect_platform"]
        redeploy__plugins__builtin__systemd_reload__systemd_reload["systemd_reload"]
        redeploy__plugins__builtin__notify___notify_slack["_notify_slack"]
        redeploy__plugins__builtin__hardware_diagnostic___get_network_interfaces["_get_network_interfaces"]
        redeploy__plugins__load_user_plugins["load_user_plugins"]
        redeploy__plugins__builtin__browser_reload__browser_reload["browser_reload"]
        redeploy__plugins__builtin__hardware_diagnostic__hardware_diagnostic["hardware_diagnostic"]
        redeploy__plugins__register_plugin["register_plugin"]
        redeploy__plugins__builtin__notify___http_post["_http_post"]
        redeploy__plugins__builtin__hardware_diagnostic___check_gpio["_check_gpio"]
        redeploy__plugins___load_builtin_plugins["_load_builtin_plugins"]
        redeploy__plugins__builtin__hardware_diagnostic___analyze_hardware["_analyze_hardware"]
        redeploy__plugins__builtin__notify___notify_webhook["_notify_webhook"]
        redeploy__plugins__builtin__notify___fmt["_fmt"]
        redeploy__plugins__builtin__process_control___find_pid_on_port["_find_pid_on_port"]
        redeploy__plugins__builtin__hardware_diagnostic___get_memory_mb["_get_memory_mb"]
        redeploy__plugins__builtin__notify___resolve_env["_resolve_env"]
        redeploy__plugins__PluginRegistry___ensure_builtins["_ensure_builtins"]
        redeploy__plugins__builtin__hardware_diagnostic___get_usb_devices["_get_usb_devices"]
        redeploy__plugins__builtin__hardware_diagnostic___get_audio_devices["_get_audio_devices"]
        redeploy__plugins__builtin__hardware_diagnostic___get_storage_gb["_get_storage_gb"]
        redeploy__plugins__builtin__process_control__process_control["process_control"]
        redeploy__plugins__builtin__hardware_diagnostic___get_cpu_info["_get_cpu_info"]
        redeploy__plugins__builtin__notify__notify["notify"]
    end
    subgraph redeploy__schema
        redeploy__schema___git_branch["_git_branch"]
        redeploy__schema__build_schema["build_schema"]
        redeploy__schema___read_version["_read_version"]
        redeploy__schema___iac_info["_iac_info"]
        redeploy__schema___discover_specs["_discover_specs"]
    end
    subgraph redeploy__spec_loader
        redeploy__spec_loader__load_migration_spec["load_migration_spec"]
    end
    subgraph redeploy__steps
        redeploy__steps__StepLibrary__all["all"]
        redeploy__steps__StepLibrary__list["list"]
    end
    subgraph redeploy__version
        redeploy__version__commits__format_analysis_report["format_analysis_report"]
        redeploy__version__changelog__ChangelogManager___categorize_commits["_categorize_commits"]
        redeploy__version__bump__bump_version["bump_version"]
        redeploy__version__read_remote_version["read_remote_version"]
        redeploy__version__manifest__VersionManifest__list_packages["list_packages"]
        redeploy__version__commits__parse_conventional["parse_conventional"]
        redeploy__version__transaction__VersionBumpTransaction___stage_one["_stage_one"]
        redeploy__version__commits__analyze_commits["analyze_commits"]
        redeploy__version__bump__verify_sources["verify_sources"]
        redeploy__version__bump__bump_package["bump_package"]
        redeploy__version__bump___calculate_bump["_calculate_bump"]
        redeploy__version__diff__diff_manifest_vs_spec["diff_manifest_vs_spec"]
        redeploy__version__diff__diff_manifest_vs_live["diff_manifest_vs_live"]
        redeploy__version__sources__get_adapter["get_adapter"]
        redeploy__version__bump__bump_version_with_git["bump_version_with_git"]
        redeploy__version__changelog__get_commits_since_tag["get_commits_since_tag"]
        redeploy__version__bump__bump_all_packages["bump_all_packages"]
    end
    redeploy__schema__build_schema --> redeploy__schema___read_version
    redeploy__schema__build_schema --> redeploy__schema___git_branch
    redeploy__schema__build_schema --> redeploy__schema___discover_specs
    redeploy__schema__build_schema --> redeploy__schema___iac_info
    redeploy__observe__DeployAuditLog__record --> redeploy__steps__StepLibrary__list
    redeploy__heal__collect_diagnostics --> redeploy__heal___ssh
    redeploy__heal__HealLoopDetector__observe --> redeploy__steps__StepLibrary__all
    redeploy__heal__HealRunner___reload_migration --> redeploy__spec_loader__load_migration_spec
    redeploy__heal__HealRunner___collect_diag_with_hint --> redeploy__heal__collect_diagnostics
    redeploy__heal__HealRunner___ask_and_apply_fix --> redeploy__heal__ask_llm
    redeploy__heal__HealRunner___ask_and_apply_fix --> redeploy__heal__apply_fix_to_spec
    redeploy__heal__HealRunner___record_repair --> redeploy__heal__write_repair_log
    redeploy__heal__HealRunner__run --> redeploy__heal__write_repair_log
    redeploy__heal__HealRunner__run --> redeploy__heal__parse_failed_step
    redeploy__parse__parse_diagnostics --> redeploy__parse___parse_section_line
    redeploy__parse___parse_section_line --> redeploy__parse___apply_system_line
    redeploy__parse___parse_section_line --> redeploy__parse__parse_container_line
    redeploy__parse___parse_section_line --> redeploy__parse___apply_git_line
    redeploy__parse___parse_section_line --> redeploy__parse___apply_health_line
    redeploy__parse___parse_section_line --> redeploy__parse___apply_network_line
    redeploy__fleet__Fleet____init__ --> redeploy__steps__StepLibrary__list
    redeploy__fleet__Fleet__from_registry --> redeploy__steps__StepLibrary__list
    redeploy__fleet__Fleet__merge --> redeploy__steps__StepLibrary__list
    redeploy__spec_loader__load_migration_spec --> redeploy__markpact__compiler__compile_markpact_document
    redeploy__spec_loader__load_migration_spec --> redeploy__markpact__parser__parse_markpact_file
    redeploy__patterns__BlueGreenPattern__expand --> redeploy__patterns___step
    redeploy__patterns__CanaryPattern__expand --> redeploy__patterns___step
    redeploy__patterns__RollbackOnFailurePattern__expand --> redeploy__patterns___step
    redeploy__patterns__list_patterns --> redeploy__steps__StepLibrary__list
    redeploy__discovery___scan_arp_cache --> redeploy__discovery___run
    redeploy__discovery___scan_mdns --> redeploy__discovery___run
    redeploy__discovery___scan_mdns --> redeploy__discovery___is_ip
    redeploy__discovery___ping_sweep --> redeploy__steps__StepLibrary__list
    redeploy__discovery___probe_ssh --> redeploy__steps__StepLibrary__list
    redeploy__discovery___detect_local_subnet --> redeploy__discovery___run
    redeploy__discovery___merge --> redeploy__steps__StepLibrary__list
    redeploy__discovery__discover --> redeploy__discovery___merge
    redeploy__discovery__discover --> redeploy__discovery___scan_known_hosts
    redeploy__discovery__discover --> redeploy__discovery___scan_arp_cache
    redeploy__discovery__discover --> redeploy__discovery___probe_ssh
    redeploy__discovery___try_ssh_credentials --> redeploy__discovery___tcp_reachable
    redeploy__discovery___detect_strategy_remote --> redeploy__discovery___build_probe_command
    redeploy__discovery___detect_strategy_remote --> redeploy__discovery___build_ssh_command
    redeploy__discovery___detect_strategy_remote --> redeploy__discovery___run_ssh_probe
    redeploy__discovery___detect_strategy_remote --> redeploy__discovery___parse_probe_output
    redeploy__discovery___detect_strategy_remote --> redeploy__discovery___infer_strategy
    redeploy__discovery__auto_probe --> redeploy__discovery___parse_probe_input
    redeploy__discovery__auto_probe --> redeploy__discovery___collect_ssh_keys
    redeploy__discovery__auto_probe --> redeploy__discovery___try_ssh_credentials
    redeploy__discovery__auto_probe --> redeploy__discovery___detect_strategy_remote
    redeploy__mcp_server___run --> redeploy__mcp_server___redeploy_bin
    redeploy__mcp_server__schema --> redeploy__schema__build_schema
    redeploy__mcp_server__plan_spec --> redeploy__mcp_server___run
    redeploy__mcp_server__run_spec --> redeploy__mcp_server___run
    redeploy__mcp_server__fix_spec --> redeploy__mcp_server___run
    redeploy__mcp_server__bump_version --> redeploy__mcp_server___run
    redeploy__mcp_server__diagnose --> redeploy__mcp_server___run
    redeploy__mcp_server__list_specs --> redeploy__schema__build_schema
    redeploy__mcp_server__exec_ssh --> redeploy__mcp_server___validate_exec_ssh_inputs
    redeploy__mcp_server__nlp_command --> redeploy__mcp_server___run
    redeploy__mcp_server__get_workspace --> redeploy__schema__build_schema
    redeploy__detect__detector__Detector__run --> redeploy__detect__probes__probe_runtime
    redeploy__detect__detector__Detector__run --> redeploy__detect__probes__probe_ports
    redeploy__detect__detector__Detector__run --> redeploy__detect__probes__probe_iptables_dnat
    redeploy__detect__hardware__probe_hardware --> redeploy__detect__hardware___wrap_remote_probe
    redeploy__detect__hardware__probe_hardware --> redeploy__integrations__op3_bridge__snapshot_to_hardware_info
    redeploy__detect__hardware__probe_hardware --> redeploy__steps__StepLibrary__list
    redeploy__detect__hardware_rules__analyze --> redeploy__detect__hardware_rules___hw_info_to_dict
    redeploy__detect__hardware_rules__analyze --> redeploy__detect__hardware_rules___op3_diag_to_hw_diag
    redeploy__detect__templates___build_templates --> redeploy__detect__templates___load_templates_from_yaml
    redeploy__detect__templates__TemplateEngine__detect --> redeploy__detect__templates__build_context
    redeploy__detect__workflow__DetectionWorkflow___collect_hosts --> redeploy__steps__StepLibrary__list
    redeploy__detect__workflow__DetectionWorkflow___collect_hosts --> redeploy__discovery__discover
    redeploy__detect__workflow__DetectionWorkflow___probe_ssh --> redeploy__discovery__auto_probe
    redeploy__detect__probes__detect_conflicts --> redeploy__steps__StepLibrary__list
    redeploy__heal__hint_provider__collect_diagnostics --> redeploy__heal__hint_provider___ssh
    redeploy__heal__hint_provider__ask_llm --> redeploy__heal__hint_provider___extract_step_block
    redeploy__heal__hint_provider__apply_fix_to_spec --> redeploy__heal__hint_provider___parse_step_block
    redeploy__heal__loop_detector__HealLoopDetector__observe --> redeploy__steps__StepLibrary__all
    redeploy__heal__runner__HealRunner___reload_migration --> redeploy__spec_loader__load_migration_spec
    redeploy__heal__runner__HealRunner___heal_step --> redeploy__heal__parse_failed_step
    redeploy__heal__runner__HealRunner___heal_step --> redeploy__heal__collect_diagnostics
    redeploy__heal__runner__HealRunner___heal_step --> redeploy__heal__ask_llm
    redeploy__heal__runner__HealRunner__run --> redeploy__heal__write_repair_log
    redeploy__config_apply__applier__apply_config_dict --> redeploy__config_apply__applier___normalize_hardware
    redeploy__config_apply__applier__apply_config_dict --> redeploy__apply__state_apply__apply_state
    redeploy__config_apply__applier__apply_config_file --> redeploy__config_apply__loader__load_config_file
    redeploy__config_apply__applier__apply_config_file --> redeploy__config_apply__applier__apply_config_dict
    redeploy__config_apply__handlers__display__apply_display_transform --> redeploy__config_apply__handlers__display___validate_display_inputs
    redeploy__models__manifest__ProjectManifest__find_and_load --> redeploy__steps__StepLibrary__list
    redeploy__models__manifest__ProjectManifest__find_and_load --> redeploy__dsl__loader__load_css
    redeploy__models__manifest__ProjectManifest__find_css --> redeploy__steps__StepLibrary__list
    redeploy__models__spec___migrate_legacy_post_deploy --> redeploy__steps__StepLibrary__list
    redeploy__models__spec__MigrationSpec__from_file --> redeploy__models__spec___migrate_legacy_post_deploy
    redeploy__models__spec__MigrationSpec__to_target_config --> redeploy__steps__StepLibrary__list
    redeploy__cli__display__print_inspect_workflows --> redeploy__cli__display___get_plugin_hint
    redeploy__cli__display__print_inspect_workflows --> redeploy__cli__display___format_workflow_header
    redeploy__cli__display__print_inspect_workflows --> redeploy__cli__display___print_workflow_step
    redeploy__cli__display__print_workflow_host_details --> redeploy__cli__display___print_host_header
    redeploy__cli__display__print_workflow_host_details --> redeploy__cli__display___print_template_match
    redeploy__cli__display__print_workflow_host_details --> redeploy__cli__display___print_alternatives
    redeploy__cli__display__generate_workflow_output_css --> redeploy__dsl__loader__manifest_to_css
    redeploy__cli__display__generate_workflow_output_css --> redeploy__dsl__loader__templates_to_css
    redeploy__cli__display__print_import_spec --> redeploy__cli__display___get_status_color
    redeploy__cli__display__print_import_spec --> redeploy__cli__display___print_spec_metadata
    redeploy__cli__display__print_import_spec --> redeploy__cli__display___print_services_table
    redeploy__cli__cli --> redeploy__cli___setup_logging
    redeploy__cli___resolve_device --> redeploy__discovery__auto_probe
    redeploy__cli__core__load_spec_or_exit --> redeploy__spec_loader__load_migration_spec
    redeploy__cli__core__find_manifest_path --> redeploy__steps__StepLibrary__list
    redeploy__cli__core__resolve_device --> redeploy__discovery__auto_probe
    redeploy__cli__core__load_spec_with_manifest --> redeploy__cli__core__load_spec_or_exit
    redeploy__cli__core__run_detect_workflow --> redeploy__cli__display__print_workflow_summary_table
    redeploy__cli__core__run_detect_workflow --> redeploy__cli__display__print_workflow_host_details
    redeploy__cli__core__run_detect_workflow --> redeploy__cli__display__generate_workflow_output_css
    redeploy__cli__core__run_detect_workflow --> redeploy__cli__display__generate_workflow_output_yaml
    redeploy__cli__commands__target__target --> redeploy__cli__core__resolve_device
    redeploy__cli__commands__target__target --> redeploy__cli__core__load_spec_with_manifest
    redeploy__cli__commands__state___get_state_path --> redeploy__cli__core__load_spec_or_exit
    redeploy__cli__commands__state___get_state_path --> redeploy__apply__state__default_state_path
    redeploy__cli__commands__state__state_cmd --> redeploy__cli__commands__state___get_state_path
    redeploy__cli__commands__state__state_cmd --> redeploy__cli__commands__state___show_checkpoint
    redeploy__cli__commands__state__state_cmd --> redeploy__cli__commands__state___list_checkpoints
    redeploy__cli__commands__inspect__inspect --> redeploy__cli__commands__inspect___find_css_path
    redeploy__cli__commands__inspect__inspect --> redeploy__dsl__loader__load_css
    redeploy__cli__commands__inspect__inspect --> redeploy__cli__display__print_inspect_app_metadata
    redeploy__cli__commands__inspect__inspect --> redeploy__cli__display__print_inspect_environments
    redeploy__cli__commands__inspect__inspect --> redeploy__cli__display__print_inspect_templates
    redeploy__cli__commands__inspect__inspect --> redeploy__cli__display__print_inspect_workflows
    redeploy__cli__commands__device_map_renderers__render_rich --> redeploy__cli__commands__device_map_renderers___build_issues_table
    redeploy__cli__commands__device_map_renderers__render_rich --> redeploy__cli__commands__device_map_renderers___build_header_panel
    redeploy__cli__commands__device_map_renderers__render_rich --> redeploy__cli__commands__device_map_renderers___build_drm_table
    redeploy__cli__commands__device_map_renderers__render_rich --> redeploy__cli__commands__device_map_renderers___build_services_table
    redeploy__cli__commands__bump_fix___find_spec --> redeploy__cli__commands__bump_fix___prompt_choose_spec
    redeploy__cli__commands__bump_fix___bump_version_file --> redeploy__cli__commands__bump_fix___bump_patch
    redeploy__cli__commands__bump_fix___update_migration_header --> redeploy__cli__commands__bump_fix___update_quadlet_service_version
    redeploy__cli__commands__bump_fix__bump_cmd --> redeploy__cli__commands__bump_fix___find_spec
    redeploy__cli__commands__bump_fix__bump_cmd --> redeploy__cli__commands__bump_fix___find_version_file
    redeploy__cli__commands__bump_fix___detect_version --> redeploy__cli__commands__bump_fix___find_version_file
    redeploy__cli__commands__exec___exec_cmd --> redeploy__cli__commands__exec____extract_script_for_ref
    redeploy__cli__commands__exec____extract_all_scripts --> redeploy__cli__commands__exec____extract_script_for_ref
    redeploy__cli__commands__exec____extract_script_for_ref --> redeploy__markpact__parser__resolve_script_ref
    redeploy__cli__commands__blueprint___execute_query_blueprint --> redeploy__cli__query__execute_query
    redeploy__cli__commands__blueprint__show --> redeploy__cli__commands__blueprint___execute_query_blueprint
    redeploy__cli__commands__export__export_cmd --> redeploy__cli__commands__export___find_export_source
    redeploy__cli__commands__export__export_cmd --> redeploy__cli__commands__export___load_manifest_from_css
    redeploy__cli__commands__export___find_export_source --> redeploy__steps__StepLibrary__list
    redeploy__cli__commands__export___load_manifest_from_css --> redeploy__dsl__loader__load_css
    redeploy__cli__commands__export___export_to_css --> redeploy__dsl__loader__manifest_to_css
    redeploy__cli__commands__export___export_to_css --> redeploy__dsl__loader__templates_to_css
    redeploy__cli__commands__mcp_cmd__mcp_cmd --> redeploy__mcp_server__serve
    redeploy__cli__commands__plugin__plugin_cmd --> redeploy__plugins__load_user_plugins
    redeploy__cli__commands__import____print_plugin_templates --> redeploy__cli__commands__import____plugin_templates
    redeploy__cli__commands__import____copy_plugin_template --> redeploy__cli__commands__import____plugin_templates
    redeploy__cli__commands__import____copy_plugin_template --> redeploy__cli__commands__import____examples_plugin_dir
    redeploy__cli__commands__plan_apply___apply_manifest_to_spec --> redeploy__cli__core__find_manifest_path
    redeploy__cli__commands__plan_apply___write_markdown_report --> redeploy__cli__commands__plan_apply___resolve_audit_entry
    redeploy__cli__commands__plan_apply___write_markdown_report --> redeploy__cli__commands__plan_apply___build_checksum_verification
    redeploy__cli__commands__plan_apply___write_markdown_report --> redeploy__cli__commands__plan_apply___default_report_path
    redeploy__cli__commands__plan_apply___write_markdown_report --> redeploy__cli__commands__plan_apply___render_markdown_report
    redeploy__cli__commands__gh_workflow___resolve_repo_root --> redeploy__cli__commands__gh_workflow___find_repo_root
    redeploy__cli__commands__gh_workflow___collect_workflow_meta --> redeploy__cli__commands__gh_workflow___load_yaml
    redeploy__cli__commands__gh_workflow___collect_workflow_meta --> redeploy__cli__commands__gh_workflow___on_section
    redeploy__cli__commands__gh_workflow___collect_workflow_meta --> redeploy__steps__StepLibrary__list
    redeploy__cli__commands__gh_workflow___collect_workflow_meta --> redeploy__cli__commands__gh_workflow___trigger_list
    redeploy__cli__commands__gh_workflow___collect_workflow_meta --> redeploy__cli__commands__gh_workflow___has_workflow_dispatch
    redeploy__cli__commands__gh_workflow___resolve_workflow_identifier --> redeploy__cli__commands__gh_workflow___collect_workflow_meta
    redeploy__cli__commands__gh_workflow__gh_workflow_list --> redeploy__cli__commands__gh_workflow___resolve_repo_root
    redeploy__cli__commands__gh_workflow__gh_workflow_list --> redeploy__cli__commands__gh_workflow___workflows_dir
    redeploy__cli__commands__gh_workflow__gh_workflow_analyze --> redeploy__cli__commands__gh_workflow___resolve_repo_root
    redeploy__cli__commands__gh_workflow__gh_workflow_analyze --> redeploy__cli__commands__gh_workflow___workflows_dir
    redeploy__cli__commands__gh_workflow__gh_workflow_analyze --> redeploy__cli__commands__gh_workflow___collect_workflow_meta
    redeploy__cli__commands__gh_workflow__gh_workflow_run --> redeploy__cli__commands__gh_workflow___resolve_repo_root
    redeploy__cli__commands__gh_workflow__gh_workflow_run --> redeploy__cli__commands__gh_workflow___workflows_dir
    redeploy__cli__commands__device_map___execute_query_device_map --> redeploy__cli__query__execute_query
    redeploy__cli__commands__device_map___render --> redeploy__cli__commands__device_map_renderers__render_yaml
    redeploy__cli__commands__device_map___render --> redeploy__cli__commands__device_map_renderers__render_json
    redeploy__cli__commands__device_map___render --> redeploy__cli__commands__device_map_renderers__render_rich
    redeploy__cli__commands__hardware___probe_hardware --> redeploy__detect__detector__Detector__probe_hardware
    redeploy__cli__commands__hardware___apply_transform --> redeploy__config_apply__handlers__display__apply_display_transform
    redeploy__cli__commands__hardware___execute_query --> redeploy__cli__query__execute_query
    redeploy__cli__commands__hardware___apply_fix --> redeploy__hardware__fixes__generate_fix_plan
    redeploy__cli__commands__hardware___apply_fix --> redeploy__fleet__Fleet__get
    redeploy__cli__commands__hardware___apply_fix --> redeploy__apply__handlers__run_ssh
    redeploy__cli__commands__lint__lint --> redeploy__cli__core__load_spec_or_exit
    redeploy__cli__commands__prompt_cmd__prompt_cmd --> redeploy__schema__build_schema
    redeploy__cli__commands__workflow__workflow_cmd --> redeploy__dsl__loader__load_css
    redeploy__cli__commands__workflow__workflow_cmd --> redeploy__cli__commands__workflow___execute_workflow
    redeploy__cli__commands__diagnose__diagnose --> redeploy__audit__audit_spec
    redeploy__cli__commands__version__monorepo___set_monorepo_version --> redeploy__cli__commands__version__monorepo___create_version_set_git
    redeploy__cli__commands__version__monorepo___set_monorepo_version --> redeploy__cli__commands__version__monorepo___print_monorepo_set_dry_run
    redeploy__cli__commands__version__monorepo___set_monorepo_version --> redeploy__cli__commands__version__monorepo___create_version_set_taggers
    redeploy__cli__commands__version__monorepo___set_monorepo_version --> redeploy__version__bump__bump_package
    redeploy__cli__commands__version__monorepo___create_version_set_git --> redeploy__cli__commands__version__helpers___resolve_package_release_git_config
    redeploy__cli__commands__version__monorepo___create_version_set_taggers --> redeploy__cli__commands__version__helpers___resolve_package_release_git_config
    redeploy__cli__commands__version__monorepo___finalize_monorepo_version_set --> redeploy__cli__commands__version__release___create_release_tags
    redeploy__cli__commands__version__commands__version_list --> redeploy__cli__commands__version__helpers___resolve_monorepo_targets
    redeploy__cli__commands__version__commands__version_list --> redeploy__version__bump__verify_sources
    redeploy__cli__commands__version__commands__version_verify --> redeploy__cli__commands__version__helpers___resolve_monorepo_targets
    redeploy__cli__commands__version__commands__version_verify --> redeploy__version__bump__verify_sources
    redeploy__cli__commands__version__commands__version_verify --> redeploy__cli__commands__version__helpers___print_verify_result
    redeploy__cli__commands__version__helpers___build_package_version_manifest --> redeploy__cli__commands__version__helpers___resolve_package_release_git_config
    redeploy__cli__commands__version__helpers___build_package_version_manifest --> redeploy__cli__commands__version__helpers___resolve_package_release_changelog_config
    redeploy__cli__commands__version__helpers___load_spec_version_diff --> redeploy__version__diff__diff_manifest_vs_spec
    redeploy__cli__commands__version__helpers___load_live_version_diff --> redeploy__version__read_remote_version
    redeploy__cli__commands__version__helpers___load_live_version_diff --> redeploy__version__diff__diff_manifest_vs_live
    redeploy__cli__commands__version__helpers___run_version_diff_for_manifest --> redeploy__version__bump__verify_sources
    redeploy__cli__commands__version__helpers___run_version_diff_for_manifest --> redeploy__cli__commands__version__helpers___print_source_drift_status
    redeploy__cli__commands__version__helpers___run_version_diff_for_manifest --> redeploy__cli__commands__version__helpers___load_spec_version_diff
    redeploy__cli__commands__version__helpers___run_version_diff_for_manifest --> redeploy__cli__commands__version__helpers___load_live_version_diff
    redeploy__cli__commands__version__helpers___run_version_diff_for_manifest --> redeploy__steps__StepLibrary__all
    redeploy__cli__commands__version__helpers___bump_single --> redeploy__version__commits__analyze_commits
    redeploy__cli__commands__version__helpers___bump_single --> redeploy__version__bump___calculate_bump
    redeploy__cli__commands__version__helpers___bump_single --> redeploy__version__commits__format_analysis_report
    redeploy__cli__commands__version__release___update_release_changelog --> redeploy__version__changelog__get_commits_since_tag
    redeploy__cli__commands__version__release___create_release_tags --> redeploy__cli__commands__version__release___format_release_tag
    redeploy__cli__commands__version__release___update_monorepo_release_changelogs --> redeploy__cli__commands__version__release___update_release_changelog
    redeploy__cli__commands__version__release___update_monorepo_release_changelogs --> redeploy__cli__commands__version__release___format_release_tag
    redeploy__cli__commands__version__release___update_monorepo_release_changelogs --> redeploy__cli__commands__version__release___resolve_package_release_changelog_config
    redeploy__cli__commands__version__scanner___detect_version_sources_in_dir --> redeploy__cli__commands__version__scanner___version_scan_specs
    redeploy__cli__commands__version__scanner___detect_version_sources_in_dir --> redeploy__cli__commands__version__scanner___regex_version_scan_specs
    redeploy__cli__commands__version__scanner___detect_version_sources_in_dir --> redeploy__cli__commands__version__scanner___is_scannable_version_path
    redeploy__cli__commands__version__scanner___detect_source_version --> redeploy__cli__commands__version__scanner___read_detected_source_versions
    redeploy__cli__commands__version__scanner___read_detected_source_versions --> redeploy__version__sources__get_adapter
    redeploy__cli__commands__version__scanner___report_version_scan_conflict --> redeploy__cli__commands__version__scanner___read_detected_source_versions
    redeploy__cli__commands__version__scanner___print_version_scan_review --> redeploy__cli__commands__version__scanner___print_version_scan_group
    redeploy__cli__commands__version__scanner___summarize_version_scan_group --> redeploy__cli__commands__version__scanner___read_detected_source_versions
    redeploy__cli__commands__version__scanner___summarize_version_scan_group --> redeploy__cli__commands__version__scanner___classify_version_scan_source_confidence
    redeploy__cli__commands__version__scanner___print_version_scan_group --> redeploy__cli__commands__version__scanner___summarize_version_scan_group
    redeploy__cli__commands__version__scanner___print_version_scan_group --> redeploy__cli__commands__version__scanner___format_version_scan_source_status
    redeploy__cli__commands__version__scanner___review_detected_sources_interactively --> redeploy__cli__commands__version__scanner___iter_version_scan_groups
    redeploy__cli__commands__version__scanner___review_detected_sources_interactively --> redeploy__cli__commands__version__scanner___summarize_version_scan_group
    redeploy__cli__commands__version__scanner___review_detected_sources_interactively --> redeploy__cli__commands__version__scanner___format_version_scan_source_status
    redeploy__cli__commands__version__scanner___review_detected_sources_interactively --> redeploy__cli__commands__version__scanner___default_keep_scanned_source
    redeploy__cli__commands__version__scanner___scan_package_version_manifests --> redeploy__cli__commands__version__scanner___detect_version_sources_in_dir
    redeploy__cli__commands__version__scanner___scan_package_version_manifests --> redeploy__cli__commands__version__scanner___derive_scanned_package_name
    redeploy__plugins__PluginRegistry__names --> redeploy__steps__StepLibrary__list
    redeploy__plugins__PluginRegistry___ensure_builtins --> redeploy__plugins___load_builtin_plugins
    redeploy__plugins__builtin__notify__notify --> redeploy__plugins__register_plugin
    redeploy__plugins__builtin__notify__notify --> redeploy__plugins__builtin__notify___notify_slack
    redeploy__plugins__builtin__notify__notify --> redeploy__plugins__builtin__notify___notify_webhook
    redeploy__plugins__builtin__notify___notify_slack --> redeploy__plugins__builtin__notify___resolve_env
    redeploy__plugins__builtin__notify___notify_slack --> redeploy__plugins__builtin__notify___fmt
    redeploy__plugins__builtin__notify___notify_slack --> redeploy__plugins__builtin__notify___http_post
    redeploy__plugins__builtin__notify___notify_webhook --> redeploy__plugins__builtin__notify___resolve_env
    redeploy__plugins__builtin__notify___notify_webhook --> redeploy__plugins__builtin__notify___fmt
    redeploy__plugins__builtin__notify___notify_webhook --> redeploy__plugins__builtin__notify___http_post
    redeploy__plugins__builtin__process_control__process_control --> redeploy__plugins__register_plugin
    redeploy__plugins__builtin__process_control__process_control --> redeploy__plugins__builtin__process_control___find_pid_on_port
    redeploy__plugins__builtin__browser_reload__browser_reload --> redeploy__plugins__register_plugin
    redeploy__plugins__builtin__systemd_reload__systemd_reload --> redeploy__plugins__register_plugin
    redeploy__plugins__builtin__hardware_diagnostic___detect_platform --> redeploy__plugins__builtin__hardware_diagnostic___run_command
    redeploy__plugins__builtin__hardware_diagnostic___get_cpu_info --> redeploy__plugins__builtin__hardware_diagnostic___run_command
    redeploy__plugins__builtin__hardware_diagnostic___get_memory_mb --> redeploy__plugins__builtin__hardware_diagnostic___run_command
    redeploy__plugins__builtin__hardware_diagnostic___get_storage_gb --> redeploy__plugins__builtin__hardware_diagnostic___run_command
    redeploy__plugins__builtin__hardware_diagnostic___get_usb_devices --> redeploy__plugins__builtin__hardware_diagnostic___run_command
    redeploy__plugins__builtin__hardware_diagnostic___get_audio_devices --> redeploy__plugins__builtin__hardware_diagnostic___run_command
    redeploy__plugins__builtin__hardware_diagnostic___get_network_interfaces --> redeploy__plugins__builtin__hardware_diagnostic___run_command
    redeploy__plugins__builtin__hardware_diagnostic___analyze_hardware --> redeploy__plugins__builtin__hardware_diagnostic___get_cpu_info
    redeploy__plugins__builtin__hardware_diagnostic___analyze_hardware --> redeploy__plugins__builtin__hardware_diagnostic___get_memory_mb
    redeploy__plugins__builtin__hardware_diagnostic___analyze_hardware --> redeploy__plugins__builtin__hardware_diagnostic___get_storage_gb
    redeploy__plugins__builtin__hardware_diagnostic___analyze_hardware --> redeploy__plugins__builtin__hardware_diagnostic___check_gpio
    redeploy__plugins__builtin__hardware_diagnostic___analyze_hardware --> redeploy__plugins__builtin__hardware_diagnostic___get_usb_devices
    redeploy__plugins__builtin__hardware_diagnostic___analyze_hardware --> redeploy__plugins__builtin__hardware_diagnostic___get_audio_devices
    redeploy__plugins__builtin__hardware_diagnostic___analyze_hardware --> redeploy__plugins__builtin__hardware_diagnostic___get_network_interfaces
    redeploy__plugins__builtin__hardware_diagnostic___analyze_hardware --> redeploy__plugins__builtin__hardware_diagnostic___detect_platform
    redeploy__plugins__builtin__hardware_diagnostic__hardware_diagnostic --> redeploy__plugins__register_plugin
    redeploy__plugins__builtin__hardware_diagnostic__hardware_diagnostic --> redeploy__plugins__builtin__hardware_diagnostic___analyze_hardware
    redeploy__dsl_python__steps__version_check --> redeploy__dsl_python__steps__ssh
    redeploy__dsl_python__runner__PythonMigrationRunner__list_migrations --> redeploy__steps__StepLibrary__list
    redeploy__hardware__config_txt__ensure_lines --> redeploy__hardware__config_txt__ensure_line
    redeploy__hardware__fixes__fix_dsi_not_enabled --> redeploy__hardware__fixes___detect_port
    redeploy__hardware__fixes__fix_dsi_not_enabled --> redeploy__hardware__panels__infer_from_hardware
    redeploy__hardware__fixes__fix_dsi_not_enabled --> redeploy__hardware__fixes___step
    redeploy__hardware__fixes__fix_enable_i2c --> redeploy__hardware__fixes___step
    redeploy__hardware__fixes__fix_enable_spi --> redeploy__hardware__fixes___step
    redeploy__hardware__fixes__generate_fix_plan --> redeploy__hardware__fixes__fix_dsi_not_enabled
    redeploy__hardware__kiosk__browsers__BrowserKioskProfile__build_launch_cmd --> redeploy__steps__StepLibrary__list
    redeploy__markpact__parser__parse_markpact_file --> redeploy__markpact__parser__parse_markpact_text
    redeploy__markpact__parser__parse_markpact_text --> redeploy__markpact__parser___parse_markpact_fence_info
    redeploy__markpact__parser__parse_markpact_file_with_refs --> redeploy__markpact__parser__parse_markpact_text
    redeploy__markpact__parser__parse_markpact_file_with_refs --> redeploy__markpact__parser___parse_markpact_fence_info
    redeploy__markpact__parser__extract_script_from_markdown --> redeploy__markpact__parser___normalize_section_id
    redeploy__markpact__parser__extract_script_from_markdown --> redeploy__markpact__parser___check_heading
    redeploy__markpact__parser__extract_script_from_markdown --> redeploy__markpact__parser___handle_fence_line
    redeploy__markpact__parser__resolve_script_ref --> redeploy__markpact__parser__extract_script_by_ref
    redeploy__markpact__parser__resolve_script_ref --> redeploy__markpact__parser__extract_script_from_markdown
    redeploy__markpact__compiler__compile_markpact_document --> redeploy__markpact__compiler__compile_markpact_document_to_data
    redeploy__markpact__compiler__compile_markpact_document --> redeploy__models__spec___migrate_legacy_post_deploy
    redeploy__markpact__compiler__compile_markpact_document_to_data --> redeploy__markpact__compiler___load_block_payload
    redeploy__markpact__compiler__compile_markpact_document_to_data --> redeploy__markpact__compiler___extract_steps
    redeploy__markpact__compiler__compile_markpact_document_to_data --> redeploy__markpact__compiler___normalize_config_payload
    redeploy__markpact__compiler__compile_markpact_document_to_data --> redeploy__markpact__compiler___deep_merge
    redeploy__markpact__compiler___normalize_config_payload --> redeploy__models__spec___migrate_legacy_post_deploy
    redeploy__apply__state__state_key --> redeploy__apply__state___slug
    redeploy__apply__state__default_state_path --> redeploy__apply__state__state_key
    redeploy__apply__state__ResumeState__save --> redeploy__apply__state___now_iso
    redeploy__apply__state__ResumeState__reset --> redeploy__apply__state___now_iso
    redeploy__apply__state_apply__HardwareStateHandler__apply --> redeploy__apply__state_apply___update_kanshi
    redeploy__apply__state_apply__apply_state --> redeploy__apply__state_apply__detect_handler
    redeploy__apply__handlers__run_ssh --> redeploy__apply__handlers___format_step_output
    redeploy__apply__handlers__run_scp --> redeploy__apply__handlers___format_step_output
    redeploy__apply__handlers__run_scp --> redeploy__apply__handlers___ensure_remote_parent_dir
    redeploy__apply__handlers__run_rsync --> redeploy__apply__handlers___format_step_output
    redeploy__apply__handlers__run_rsync --> redeploy__apply__handlers___ensure_remote_parent_dir
    redeploy__apply__handlers__run_docker_build --> redeploy__apply__utils__run_container_build__run_container_build
    redeploy__apply__handlers__run_podman_build --> redeploy__apply__utils__run_container_build__run_container_build
    redeploy__apply__handlers__run_docker_health_wait --> redeploy__apply__handlers___parse_container_statuses
    redeploy__apply__handlers__run_docker_health_wait --> redeploy__apply__handlers___all_containers_healthy
    redeploy__apply__handlers__run_inline_script --> redeploy__apply__handlers___resolve_command_ref
    redeploy__apply__handlers___resolve_command_ref --> redeploy__markpact__parser__resolve_script_ref
    redeploy__apply__handlers__run_ensure_config_line --> redeploy__hardware__config_txt__ensure_line
    redeploy__apply__handlers__run_raspi_config --> redeploy__hardware__raspi_config__build_raspi_config_command
    redeploy__apply__handlers__run_ensure_autostart_entry --> redeploy__hardware__kiosk__autostart__ensure_autostart_entry
    redeploy__apply__executor__Executor____init__ --> redeploy__apply__state__default_state_path
    redeploy__apply__executor__Executor___execute_step --> redeploy__apply__handlers__run_ssh
    redeploy__apply__executor__Executor___rollback --> redeploy__apply__rollback__rollback_steps
    redeploy__version__bump__bump_version --> redeploy__version__bump___calculate_bump
    redeploy__version__bump__verify_sources --> redeploy__version__sources__get_adapter
    redeploy__version__bump__bump_version_with_git --> redeploy__version__bump___calculate_bump
    redeploy__version__bump__bump_package --> redeploy__version__bump___calculate_bump
    redeploy__version__bump__bump_all_packages --> redeploy__version__bump__bump_package
    redeploy__version__transaction__VersionBumpTransaction___stage_one --> redeploy__version__sources__get_adapter
    redeploy__version__changelog__ChangelogManager___categorize_commits --> redeploy__version__commits__parse_conventional
    redeploy__version__manifest__VersionManifest__list_packages --> redeploy__steps__StepLibrary__list
    redeploy__version__commits__analyze_commits --> redeploy__version__commits__parse_conventional
    redeploy__plan__planner__Planner___plan_pattern --> redeploy__patterns__get_pattern
    redeploy__blueprint__extractor__extract_blueprint --> redeploy__blueprint__sources__compose__merge_compose_files
    redeploy__blueprint__extractor__extract_blueprint --> redeploy__blueprint__sources__hardware__build_hw_requirements
    redeploy__blueprint__extractor__extract_blueprint --> redeploy__blueprint__sources__infra__infer_app_url
    redeploy__blueprint__extractor__extract_blueprint --> redeploy__steps__StepLibrary__list
    redeploy__blueprint__sources__compose__merge_compose_files --> redeploy__blueprint__sources__compose___merge_compose
    redeploy__blueprint__sources__compose___merge_compose --> redeploy__blueprint__sources__compose___parse_compose_ports
    redeploy__blueprint__sources__compose___merge_compose --> redeploy__blueprint__sources__compose___parse_compose_volumes
    redeploy__blueprint__sources__compose___merge_compose --> redeploy__blueprint__sources__compose___parse_compose_env
    redeploy__blueprint__sources__compose___merge_compose --> redeploy__blueprint__sources__compose___parse_compose_healthcheck
    redeploy__blueprint__generators__docker_compose__generate_twin --> redeploy__blueprint__generators__docker_compose___build_service
    redeploy__integrations__op3_bridge__snapshot_to_device_map --> redeploy__integrations__op3_bridge__snapshot_to_hardware_info
    redeploy__integrations__op3_bridge__snapshot_to_device_map --> redeploy__integrations__op3_bridge__snapshot_to_infra_state
    redeploy__integrations__op3_bridge__snapshot_to_device_map --> redeploy__steps__StepLibrary__list
    redeploy__dsl__loader__load_css --> redeploy__dsl__loader___build_from_nodes
    redeploy__dsl__loader__load_css_text --> redeploy__dsl__loader___build_from_nodes
    redeploy__dsl__loader___build_from_nodes --> redeploy__dsl__loader___build_manifest
    redeploy__dsl__loader___build_from_nodes --> redeploy__dsl__loader___build_templates
    redeploy__dsl__loader___build_from_nodes --> redeploy__dsl__loader___build_workflows
    redeploy__dsl__loader__templates_to_css --> redeploy__dsl__loader___condition_key
    redeploy__dsl__parser__DSLNode____repr__ --> redeploy__steps__StepLibrary__list
    redeploy__dsl__parser__RedeployDSLParser__parse --> redeploy__dsl__parser___strip_comments
    redeploy__iac__docker_compose__DockerComposeParser___load_merged --> redeploy__markpact__compiler___deep_merge
    redeploy__iac__docker_compose__DockerComposeParser___resolve_image_and_build --> redeploy__iac__docker_compose___resolve_var
    redeploy__iac__docker_compose__DockerComposeParser___parse_service_ports --> redeploy__iac__docker_compose___parse_port
    redeploy__iac__docker_compose__DockerComposeParser___parse_service_ports --> redeploy__iac__docker_compose___resolve_var
    redeploy__iac__docker_compose__DockerComposeParser___parse_service_volumes --> redeploy__iac__docker_compose___parse_volume
    redeploy__iac__docker_compose__DockerComposeParser___parse_service_env --> redeploy__iac__docker_compose___env_dict
    redeploy__iac__docker_compose__DockerComposeParser___parse_service_env --> redeploy__iac__docker_compose___resolve_var
    redeploy__iac__docker_compose__DockerComposeParser___parse_service_networks --> redeploy__steps__StepLibrary__list
    redeploy__iac__docker_compose__DockerComposeParser___parse_service_depends_on --> redeploy__steps__StepLibrary__list
    redeploy__iac__config_hints__ConfigHintsParser___parse_k8s_yaml --> redeploy__steps__StepLibrary__list
    redeploy__iac__parsers__compose__DockerComposeParser___parse_service_networks --> redeploy__steps__StepLibrary__list
    redeploy__iac__parsers__compose__DockerComposeParser___parse_depends_on --> redeploy__steps__StepLibrary__list
    examples__redeploy_iac_parsers__helm_kustomize__HelmTemplatesParser__parse --> redeploy__steps__StepLibrary__list
    examples__redeploy_iac_parsers__gitops_ci__GitLabCIGitOpsParser__can_parse --> examples__redeploy_iac_parsers__gitops_ci___is_gitops_command
    redeploy__analyze__spec_analyzer__SpecAnalyzer____init__ --> redeploy__steps__StepLibrary__list
    redeploy__analyze__spec_analyzer__SpecAnalyzer__analyze_file --> redeploy__analyze__ignore__ensure_redeployignore
    redeploy__analyze__spec_analyzer__SpecAnalyzer__analyze_file --> redeploy__markpact__parser__parse_markpact_file
    redeploy__analyze__spec_analyzer__SpecAnalyzer__analyze_file --> redeploy__markpact__compiler__compile_markpact_document
    redeploy__analyze__ignore__IgnoreList__is_ignored --> redeploy__steps__StepLibrary__all
    redeploy__analyze__preflight_schema__generate_preflight_schema --> redeploy__analyze__preflight_schema___resolve_command_refs
    redeploy__analyze__preflight_schema__generate_preflight_schema --> redeploy__analyze__preflight_schema___collect_local_artifacts
    redeploy__analyze__preflight_schema__generate_preflight_schema --> redeploy__analyze__preflight_schema___collect_remote_checks
    redeploy__analyze__preflight_schema___resolve_command_refs --> redeploy__markpact__parser__resolve_script_ref
    redeploy__analyze__preflight_schema___collect_local_artifacts --> redeploy__analyze__models__AnalysisResult__add
    redeploy__analyze__preflight_schema___collect_local_artifacts --> redeploy__analyze__preflight_schema___resolve_local_path
    redeploy__analyze__checkers__path__PathChecker___check_field --> redeploy__analyze__checkers__path__resolve_local_path
    redeploy__analyze__checkers__path__CommandPathChecker__check --> redeploy__analyze__checkers__path__resolve_local_path
    redeploy__analyze__checkers__path__CommandPathChecker__check --> redeploy__analyze__checkers__path__is_inside
    redeploy__analyze__checkers__compose___check_env_files --> redeploy__analyze__checkers__compose___is_ignored
    redeploy__analyze__checkers__compose___check_volumes --> redeploy__analyze__checkers__compose___is_ignored
    redeploy__analyze__checkers__compose__scan_compose_file --> redeploy__analyze__checkers__compose___check_build_section
    redeploy__analyze__checkers__compose__scan_compose_file --> redeploy__analyze__checkers__compose___check_env_files
    redeploy__analyze__checkers__compose__scan_compose_file --> redeploy__analyze__checkers__compose___check_volumes
    redeploy__analyze__checkers__compose__ComposeChecker__check --> redeploy__steps__StepLibrary__list
    redeploy__analyze__checkers__compose__ComposeChecker__check --> redeploy__analyze__checkers__compose__scan_compose_file
    redeploy__analyze__checkers__command_ref__CommandRefChecker___check_external_ref --> redeploy__analyze__checkers__path__resolve_local_path
    redeploy__analyze__checkers__command_ref__CommandRefChecker___check_external_ref --> redeploy__markpact__parser__resolve_script_ref
    redeploy__analyze__checkers__binary__BinaryChecker__check --> redeploy__analyze__checkers__binary__extract_binaries
    redeploy__analyze__checkers__docker_build__DockerBuildChecker__check --> redeploy__analyze__checkers__docker_build__collect_sync_mappings
    redeploy__analyze__checkers__docker_build__DockerBuildChecker__check --> redeploy__analyze__checkers__docker_build__parse_docker_build
    redeploy__analyze__checkers__docker_build__DockerBuildChecker___check_remote_context --> redeploy__analyze__checkers__docker_build__match_local_src
    redeploy__analyze__checkers__docker_build__DockerBuildChecker___check_remote_context --> redeploy__analyze__checkers__docker_build__resolve_local_dockerfile
    redeploy__audit__audit_spec --> redeploy__spec_loader__load_migration_spec
    redeploy__audit__extractor__Extractor___from_target --> redeploy__audit__paths__extract_port
    redeploy__audit__extractor__Extractor___from_target --> redeploy__audit__paths__normalize_path
