flowchart TD
%% generated in 0.02s
    examples__redeploy_iac_parsers["examples.redeploy_iac_parsers<br/>18 funcs"]
    redeploy__analyze["redeploy.analyze<br/>41 funcs"]
    redeploy__apply["redeploy.apply<br/>75 funcs"]
    redeploy__audit["redeploy.audit<br/>33 funcs"]
    redeploy__blueprint["redeploy.blueprint<br/>14 funcs"]
    redeploy__cli["redeploy.cli<br/>212 funcs"]
    redeploy__config_apply["redeploy.config_apply<br/>6 funcs"]
    redeploy__detect["redeploy.detect<br/>43 funcs"]
    redeploy__discovery["redeploy.discovery<br/>26 funcs"]
    redeploy__dsl["redeploy.dsl<br/>20 funcs"]
    redeploy__dsl_python["redeploy.dsl_python<br/>33 funcs"]
    redeploy__fleet["redeploy.fleet<br/>23 funcs"]
    redeploy__hardware["redeploy.hardware<br/>21 funcs"]
    redeploy__heal["redeploy.heal<br/>40 funcs"]
    redeploy__iac["redeploy.iac<br/>73 funcs"]
    redeploy__integrations["redeploy.integrations<br/>5 funcs"]
    redeploy__markpact["redeploy.markpact<br/>16 funcs"]
    redeploy__mcp_server["redeploy.mcp_server<br/>15 funcs"]
    redeploy__models["redeploy.models<br/>30 funcs"]
    redeploy__observe["redeploy.observe<br/>14 funcs"]
    redeploy__patterns["redeploy.patterns<br/>11 funcs"]
    redeploy__plan["redeploy.plan<br/>21 funcs"]
    redeploy__plugins["redeploy.plugins<br/>36 funcs"]
    redeploy__schema["redeploy.schema<br/>6 funcs"]
    redeploy__spec_loader["redeploy.spec_loader<br/>1 funcs"]
    redeploy__steps["redeploy.steps<br/>12 funcs"]
    redeploy__version["redeploy.version<br/>88 funcs"]
    redeploy__cli ==>|16| redeploy__version
    redeploy__cli ==>|15| redeploy__steps
    redeploy__cli ==>|7| redeploy__dsl
    redeploy__cli ==>|7| redeploy__apply
    redeploy__iac ==>|7| redeploy__steps
    redeploy__cli ==>|6| redeploy__discovery
    redeploy__analyze ==>|5| redeploy__markpact
    redeploy__models ==>|4| redeploy__steps
    redeploy__cli ==>|4| redeploy__config_apply
    redeploy__fleet -->|3| redeploy__steps
    redeploy__discovery -->|3| redeploy__steps
    redeploy__mcp_server -->|3| redeploy__schema
    redeploy__detect -->|3| redeploy__steps
    redeploy__cli -->|3| redeploy__plugins
    redeploy__cli -->|3| redeploy__blueprint
    redeploy__dsl_python -->|3| redeploy__steps
    redeploy__apply -->|3| redeploy__hardware
    redeploy__analyze -->|3| redeploy__steps
    redeploy__heal -->|2| redeploy__steps
    redeploy__heal -->|2| redeploy__spec_loader
    redeploy__spec_loader -->|2| redeploy__markpact
    redeploy__detect -->|2| redeploy__discovery
    redeploy__cli -->|2| redeploy__mcp_server
    redeploy__cli -->|2| redeploy__iac
    redeploy__cli -->|2| redeploy__analyze
    redeploy__cli -->|2| redeploy__detect
    redeploy__cli -->|2| redeploy__hardware
    redeploy__markpact -->|2| redeploy__models
    redeploy__apply -->|2| redeploy__steps
    redeploy__blueprint -->|2| redeploy__steps
    redeploy__observe -->|1| redeploy__steps
    redeploy__patterns -->|1| redeploy__steps
    redeploy__detect -->|1| redeploy__integrations
    redeploy__config_apply -->|1| redeploy__apply
    redeploy__models -->|1| redeploy__dsl
    redeploy__cli -->|1| redeploy__spec_loader
    redeploy__cli -->|1| redeploy__markpact
    redeploy__cli -->|1| redeploy__integrations
    redeploy__cli -->|1| redeploy__fleet
    redeploy__cli -->|1| redeploy__schema
    redeploy__cli -->|1| redeploy__audit
    redeploy__plugins -->|1| redeploy__steps
    redeploy__dsl_python -->|1| redeploy__cli
    redeploy__hardware -->|1| redeploy__steps
    redeploy__apply -->|1| redeploy__markpact
    redeploy__version -->|1| redeploy__steps
    redeploy__plan -->|1| redeploy__steps
    redeploy__plan -->|1| redeploy__patterns
    redeploy__blueprint -->|1| redeploy__integrations
    redeploy__integrations -->|1| redeploy__steps
    redeploy__dsl -->|1| redeploy__steps
    redeploy__iac -->|1| redeploy__markpact
    examples__redeploy_iac_parsers -->|1| redeploy__steps
    redeploy__audit -->|1| redeploy__spec_loader
