"""Shared helpers for plan / apply / migrate / run commands."""
from __future__ import annotations

from pathlib import Path

from rich.console import Console

from ..core import find_manifest_path, load_spec_or_exit


def apply_manifest_to_spec(console: Console, manifest, spec, env_name: str) -> None:
    from ...models import ProjectManifest

    if manifest:
        if env_name and env_name not in manifest.environments:
            console.print(
                f"[yellow]⚠ env '{env_name}' not in redeploy.yaml — known: "
                f"{', '.join(manifest.environments) or 'none'}[/yellow]"
            )
        manifest.apply_to_spec(spec, env_name=env_name)
        env_label = f" [cyan][env: {env_name}][/cyan]" if env_name else ""
        console.print(f"[dim]manifest: {find_manifest_path()}{env_label}[/dim]")
    elif not env_name:
        dotenv_manifest = ProjectManifest.from_dotenv(Path.cwd())
        if dotenv_manifest:
            dotenv_manifest.apply_to_spec(spec)
            console.print("[dim]manifest: .env (DEPLOY_* vars)[/dim]")


def print_spec_summary(console: Console, spec) -> None:
    console.print(
        f"\n[bold]{spec.name}[/bold]"
        + (f"  [dim]{spec.description}[/dim]" if spec.description else "")
    )
    console.print(
        f"  [dim]{spec.source.strategy.value}[/dim]  →  "
        f"[bold]{spec.target.strategy.value}[/bold]"
        f"  ({spec.source.host})"
    )


def perform_live_detect(console: Console, spec):
    from ...detect import Detector
    from ...plan import Planner

    console.print(f"\n[bold]detect[/bold]  (live probe of {spec.source.host})")
    detector = Detector(
        host=spec.source.host,
        app=spec.source.app,
        domain=spec.source.domain,
    )
    state = detector.run()
    console.print(
        f"  detected: {state.detected_strategy}  "
        f"version={state.current_version or '?'}  "
        f"conflicts={len(state.conflicts)}"
    )
    planner = Planner(state, spec.to_target_config())
    planner._spec = spec
    return planner


def run_apply(
    console: Console,
    migration,
    dry_run: bool,
    output,
    *,
    ssh_key: str = "",
    progress_yaml: bool = False,
    resume: bool = False,
    from_step: str | None = None,
    state_file: str | None = None,
    no_state: bool = False,
    spec_path: str | None = None,
    parallel_jobs: int | None = None,
) -> bool:
    from ...apply import Executor

    prefix = "[DRY RUN] " if dry_run else ""
    console.print(f"\n[bold]{prefix}apply[/bold]")

    state_path = Path(state_file) if state_file else None
    if no_state:
        state_path = Path("/dev/null")

    executor = Executor(
        migration,
        dry_run=dry_run,
        ssh_key=ssh_key or None,
        progress_yaml=progress_yaml,
        resume=resume,
        from_step=from_step,
        state_path=state_path if not no_state else None,
        spec_path=spec_path,
        parallel_jobs=parallel_jobs,
    )
    if no_state:
        executor._state = None
        executor._state_path = None

    if resume and executor.state is not None and executor.state.completed_count:
        console.print(
            f"[cyan]resume:[/cyan] {executor.state.completed_count}/"
            f"{executor.state.total_steps} step(s) already done"
            + (f" — last failure: {executor.state.failed_step_id}"
               if executor.state.failed_step_id else "")
        )
    elif resume:
        console.print("[dim]resume: no prior checkpoint, running from start[/dim]")

    ok = executor.run()
    console.print(f"\n{executor.summary()}")

    if output:
        executor.save_results(Path(output))

    return ok


def load_dotenv_for_heal() -> None:
    try:
        from dotenv import load_dotenv
        for candidate in [Path(".env"), Path.home() / ".redeploy" / ".env"]:
            if candidate.exists():
                load_dotenv(candidate, override=False)
                break
    except ImportError:
        pass


def detect_project_version(spec_path: str) -> str:
    for path in [
        Path(spec_path).parent / "VERSION",
        Path(spec_path).parent.parent / "VERSION",
        Path("VERSION"),
    ]:
        if path.exists():
            return path.read_text().strip()
    return ""


def print_heal_banner(console: Console, fix_hint: str | None) -> None:
    console.print("\n[bold green]heal[/bold green] mode: [dim]on[/dim]")
    if fix_hint:
        console.print(f"[cyan]user hint:[/cyan] {fix_hint}")


def ensure_redeployignore(project_root: Path, console: Console) -> None:
    target = project_root / ".redeployignore"
    if target.exists():
        return

    lines: list[str] = [
        "# Auto-generated by redeploy on first run.",
        "# Patterns excluded from deployment sync (rsync).",
        "# .gitignore is also respected automatically.",
        "",
        ".git/",
        ".venv/",
        "venv/",
        "",
        "__pycache__/",
        "*.py[cod]",
        ".pytest_cache/",
        ".mypy_cache/",
        ".ruff_cache/",
        "node_modules/",
        "",
        "dist/",
        "build/",
        "coverage/",
        "*.log/",
        "",
        "logs/",
        "**/logs/",
    ]

    candidates = [
        "archive/",
        "docs/",
        "tests/",
        "frontend/tests/",
        ".redeploy/state/",
        ".redeploy/logs/",
        "db/logs/",
        "db/backups/",
    ]
    existing = [c for c in candidates if (project_root / c.rstrip("/")).exists()]
    if existing:
        lines += ["", "# Optional heavy/operational paths detected in this project"]
        lines += existing

    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    console.print(f"[dim]generated {target.name} (first run)[/dim]")


def inject_project_sync_step(migration, spec, project_root: Path, console: Console) -> None:
    from ...models import MigrationStep, StepAction

    if any(s.id == "sync_project_tree" for s in migration.steps):
        return

    host = (migration.host or "").strip().lower()
    if host in {"", "local", "localhost", "127.0.0.1"}:
        return

    remote_dir = (getattr(spec.target, "remote_dir", "") or "").strip()
    if not remote_dir:
        return

    sync_step = MigrationStep(
        id="sync_project_tree",
        action=StepAction.RSYNC,
        description="Sync full project tree to remote_dir (respect .gitignore/.redeployignore)",
        src=f"{project_root.as_posix().rstrip('/')}/",
        dst=f"{remote_dir.rstrip('/')}/",
        excludes=[".git/", ".redeploy/state/", ".redeploy/logs/"],
    )

    insert_at = 0
    for idx, step in enumerate(migration.steps):
        if step.id == "sync_env":
            insert_at = idx + 1
            break
    migration.steps.insert(insert_at, sync_step)
    console.print("[dim]plan: injected sync_project_tree (full rsync before apply)[/dim]")


def load_spec_for_run(console: Console, spec_file, manifest):
    resolved_spec = spec_file or (manifest.spec if manifest else "migration.yaml")
    if not Path(resolved_spec).exists():
        console.print(f"[red]✗ spec file not found: {resolved_spec}[/red]")
        console.print("[dim]  Create one with: redeploy init[/dim]")
        import sys
        sys.exit(1)
    return resolved_spec, load_spec_or_exit(console, resolved_spec)
